# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-service-connection'
    #cmd: 'oc start-build nodejs-ex --follow'
    cmd: 'oc new-app https://github.com/ally-sourced/aro03 -l name=opticca-demo'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-service-connection'
    cmd: 'oc start-build nodejs-ex --follow'    
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-service-connection'
    cmd: 'oc status'